// Generated by CoffeeScript 1.11.1
(function() {
  var a, flag, n, nums, tmp;

  nums = [1, 2, 3, 4, 5];

  tmp = [
    (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = nums.length; i < len; i++) {
        n = nums[i];
        results.push(n * 2);
      }
      return results;
    })()
  ];

  flag = true;

  if (flag) {
    a = 1;
  } else {
    a = 2;
  }

}).call(this);

//# sourceMappingURL=myFirstCoffee.js.map
